<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - others</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>others</h1>
<p>
  Test duration: 621.005s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">others.OthersTest</td>
      </tr>
            
<tr>
  <td class="method">
                  airplaneToNormalMode
      </td>
  <td class="duration">
    199.455s
  </td>
  <td class="result">
        
    
            <div class="testOutput">
                        &lt;失败截图路径 = E:\testProjects\ZengQiang\screenshots1\airplaneToNormalMode.png /&gt;<br />
                                &lt;失败截图路径 = E:\testProjects\ZengQiang\screenshots1\airplaneToNormalMode.png /&gt;<br />
                  </div>
    

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: 退出飞行模式后入网失败 expected [1] but found [0]</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:496)<br />
              org.testng.Assert.assertEquals(Assert.java:125)<br />
              org.testng.Assert.assertEquals(Assert.java:372)<br />
              others.OthersTest.airplaneToNormalMode(OthersTest.java:194)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:639)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br />
              java.lang.Thread.run(Unknown Source)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  fastDialer
      </td>
  <td class="duration">
    69.582s
  </td>
  <td class="result">
        
    
            <div class="testOutput">
                        &lt;失败截图路径 = E:\testProjects\ZengQiang\screenshots1\fastDialer.png /&gt;<br />
                                &lt;失败截图路径 = E:\testProjects\ZengQiang\screenshots1\fastDialer.png /&gt;<br />
                  </div>
    

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: 超时未接通或中途被挂断 expected [0] but found [1]</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:496)<br />
              org.testng.Assert.assertEquals(Assert.java:125)<br />
              org.testng.Assert.assertEquals(Assert.java:372)<br />
              others.OthersTest.fastDialer(OthersTest.java:79)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:639)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br />
              java.lang.Thread.run(Unknown Source)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  hotStartLocationTime
      </td>
  <td class="duration">
    68.974s
  </td>
  <td class="result">
        
    
            <div class="testOutput">
                        &lt;失败截图路径 = E:\testProjects\ZengQiang\screenshots1\hotStartLocationTime.png /&gt;<br />
                                &lt;失败截图路径 = E:\testProjects\ZengQiang\screenshots1\hotStartLocationTime.png /&gt;<br />
                  </div>
    

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: 超过60s还未定位 expected [成功] but found [失败]</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:496)<br />
              org.testng.Assert.assertEquals(Assert.java:125)<br />
              org.testng.Assert.assertEquals(Assert.java:178)<br />
              others.OthersTest.hotStartLocationTime(OthersTest.java:131)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:639)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br />
              java.lang.Thread.run(Unknown Source)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  sosToNormalMode
      </td>
  <td class="duration">
    252.304s
  </td>
  <td class="result">
        
    
            <div class="testOutput">
                        &lt;失败截图路径 = E:\testProjects\ZengQiang\screenshots1\sosToNormalMode.png /&gt;<br />
                                &lt;失败截图路径 = E:\testProjects\ZengQiang\screenshots1\sosToNormalMode.png /&gt;<br />
                  </div>
    

        <a href="javascript:toggleElement('exception-3', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: 退出sos模式后入网失败 expected [1] but found [0]</b></a><br />
    <div class="stackTrace" id="exception-3">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:496)<br />
              org.testng.Assert.assertEquals(Assert.java:125)<br />
              org.testng.Assert.assertEquals(Assert.java:372)<br />
              others.OthersTest.sosToNormalMode(OthersTest.java:165)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:639)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br />
              java.lang.Thread.run(Unknown Source)<br />
                </div>
      </td>
</tr>
      </table>


  
</body>
</html>
